name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite executar manualmente o workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Gerar Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: paulo9631 # Substitua pelo seu nome de usuário
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
